# Generated by Django 4.1.2 on 2022-10-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_recipe_user_delete_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="name",
            field=models.TextField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
