# Generated by Django 4.1.2 on 2022-10-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_ingredients_name_remove_ingredients_recipe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredients", old_name="recipe", new_name="ing_recipe",
        ),
    ]
