# Generated by Django 4.1.2 on 2022-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_rename_recipe_ingredients_ing_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="ing_recipe",
            field=models.ManyToManyField(to="polls.recipe"),
        ),
    ]
