# Generated by Django 4.1.2 on 2022-10-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_alter_ingredients_ing_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="ing_recipe",
            field=models.ManyToManyField(related_name="ingredient", to="polls.recipe"),
        ),
    ]
