# Generated by Django 4.1.2 on 2022-10-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_ingredients_ing_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="name",
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.TextField(max_length=35, unique=True),
        ),
    ]
