# Generated by Django 4.1.2 on 2022-10-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(
                default="images/rsp_default.webp", upload_to="images"
            ),
        ),
    ]
