# Generated by Django 4.1.2 on 2022-10-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0013_delete_uploadimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe", name="dummy", field=models.TextField(default="nthng"),
        ),
    ]
