# Generated by Django 4.1.2 on 2022-10-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0014_recipe_dummy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.RemoveField(model_name="recipe", name="dummy",),
        migrations.RemoveField(model_name="recipe", name="recipe_image",),
    ]
