# Generated by Django 4.1.2 on 2022-10-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0015_image_remove_recipe_dummy_remove_recipe_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default="images/007.jpg", upload_to="images"),
        ),
    ]
