# Generated by Django 4.1.2 on 2022-10-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0018_alter_ingredients_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="ingredients", name="image",),
    ]
